version: '3'

services:
  auth-db:
    container_name: 'auth-postgres'
    image: 'postgres:15'
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${AUTH_POSTGRES_PORT}
    ports:
      - '${AUTH_POSTGRES_PORT}:${AUTH_POSTGRES_PORT}'
    command: -p ${AUTH_POSTGRES_PORT}

  auth-api:
    container_name: 'auth-api'
    image: 'go-server'
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: ${AUTH_POSTGRES_PORT}
      SERVER_PORT: ${AUTH_SERVER_PORT}
    ports:
      - '${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}'
    depends_on:
      - auth-db
